# Generated by Django 3.2.8 on 2022-01-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20220117_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country_geoname_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='longitude',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_valid',
            field=models.BooleanField(default=False),
        ),
    ]
