# Generated by Django 3.2.11 on 2022-01-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20220118_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
